version: "3.3"
services:
  voter:
    build: ./vote
    depends_on:
      - redis
    ports:
      - "80:80"
  results:
    build: ./result
    ports:
      - "81:80"
    depends_on:
      - db
  worker:
    build: ./worker
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  redis:
    image: redis:alpine
